export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_ERROR = 'GET_NOTIFICATIONS_ERROR';

export const GET_MORE_NOTIFICATIONS = 'GET_MORE_NOTIFICATIONS';
export const GET_MORE_NOTIFICATIONS_SUCCESS = 'GET_MORE_NOTIFICATIONS_SUCCESS';

export const SET_SINCE = 'SET_SINCE';

export const MOVE_NOTIFICATIONS = 'MOVE_NOTIFICATIONS';

export const SET_NOTIFICATION_AS_READ = 'SET_NOTIFICATION_AS_READ';
export const SET_NOTIFICATION_AS_READ_SUCCESS = 'SET_NOTIFICATION_AS_READ_SUCCESS';
export const SET_NOTIFICATION_AS_READ_ERROR = 'SET_NOTIFICATION_AS_READ_ERROR';

export const SET_NOTIFICATION_SUBSCRIPTION = 'SET_NOTIFICATION_SUBSCRIPTION';